# Output directory where the output data will be stored; if not given, use the config file name as the output directory.
outdir:

# Suffix for the output files
result_suffix: "_results"

# Feature list
features:
  - cfg_size
  - cfg_avg_degree
  - cfg_num_degree
  - cfg_avg_loopintersize
  - cfg_avg_loopsize
  - cfg_avg_sccsize
  - cfg_num_backedges
  - cfg_num_loops
  - cfg_num_loops_inter
  - cfg_num_scc
  - cfg_sum_loopintersize
  - cfg_sum_loopsize
  - cfg_sum_sccsize
  - cg_num_callees
  - cg_num_callers
  - cg_num_imported_callees
  - cg_num_incalls
  - cg_num_outcalls
  - cg_num_imported_calls
  - inst_avg_abs_dtransfer
  - inst_avg_abs_arith
  - inst_avg_abs_ctransfer
    # dtransfer + misc
  - inst_num_abs_dtransfer
    # arith + shift
  - inst_num_abs_arith
    # ctransfer + cond ctransfer
  - inst_num_abs_ctransfer
  - inst_avg_total
  - inst_avg_floatinst
  - inst_avg_logic
  - inst_avg_dtransfer
  - inst_avg_arith
  - inst_avg_cmp
  - inst_avg_shift
  - inst_avg_bitflag
  - inst_avg_cndctransfer
  - inst_avg_ctransfer
  - inst_avg_misc
  - inst_num_total
  - inst_num_floatinst
  - inst_num_logic
  - inst_num_dtransfer
  - inst_num_arith
  - inst_num_cmp
  - inst_num_shift
  - inst_num_bitflag
  - inst_num_cndctransfer
  - inst_num_ctransfer
  - inst_num_misc
#  - data_num_consts
#  - data_avg_consts
#  - data_sum_consts_seq
#  - data_num_strings
#  - data_sum_strlen
#  - data_avg_strlen
#  - data_sum_strlen_seq
#  - data_sum_abs_strings
#  - data_avg_abs_strings
#  - data_sum_abs_strings_seq

# Corpus function details (start_address:function_name:verification_method:category)
target_funcs:
  # Examples to show corpus function definitions
  "/home/chkup/Desktop/cases/bin_corpus/httpd":
    - 004c2f90:MD5_Update:MD5:Improper_Integrity # Intergrity (w/o authenticity) verification
    - 004e80e8:getProductId:Protected:Proper_Compatibility # Compatiablity verification
    - 004e80f8:getProductVer:Protected:Proper_Freshness # Freshness verification
